"""Generate a self-contained HTML tool for hand-labeling the sentiment sample.

Reading `data/processed/sentiment_annotation_sample.csv` directly means 250
contributions in one spreadsheet column, no PM/date context surfaced, no
keyboard navigation - unpleasant for what is meant to be a couple of hours of
focused work. This script embeds the sample as JSON inside a static HTML page
with a click-through interface instead (contribution list + filters on the
left, metadata + text + label controls on the right), the same pattern the
prior trans-rights project used for its own frame-annotation tool.

Output is a plain file, not published anywhere: `data/processed/
sentiment_annotation_tool.html`, opened locally with `open <path>` or by
double-clicking. It is gitignored and regenerated by this script - the
committed artifact is the CSV it reads from and writes back to, not this page.

**What this script does not do: produce labels.** It seeds the page from
whatever is already in the CSV (blank on a first run, partially filled if
resuming), and the page autosaves to the browser's localStorage as you click.
When done, use the page's "Exporter le CSV" button and overwrite
`sentiment_annotation_sample.csv` with the download - same columns, same
order, so `annotation.load_annotations()` picks it up immediately.

Run with:

    python -m hansard_pm_nlp.annotation_tool
"""

from __future__ import annotations

import json

import pandas as pd

from hansard_pm_nlp.annotation import (
    CONTEXT_COLUMNS,
    DECISION_RULES,
    LABEL_COLUMN,
    LABEL_DEFINITIONS,
    PROCESSED_DIR,
    SAMPLE_FILENAME,
    VALID_LABELS,
)

OUTPUT_FILENAME = "sentiment_annotation_tool.html"

#: Same hex values as app.py's PM_COLORS, so a PM reads as the same color in
#: the annotation tool and the dashboard.
PM_COLORS = {
    "Boris Johnson": "#1f77b4",
    "Liz Truss": "#ff7f0e",
    "Rishi Sunak": "#2ca02c",
    "Keir Starmer": "#d62728",
}
DEFAULT_PM_COLOR = "#8a8f99"


def _load_rows() -> list[dict]:
    path = PROCESSED_DIR / SAMPLE_FILENAME
    df = pd.read_csv(path, dtype={LABEL_COLUMN: "string"})

    rows = []
    for _, row in df.iterrows():
        record = {col: row[col] for col in CONTEXT_COLUMNS}
        record["sitting_date"] = str(record["sitting_date"])[:10]
        record["is_pmqs"] = bool(record["is_pmqs"])
        label = row[LABEL_COLUMN]
        record[LABEL_COLUMN] = None if pd.isna(label) or label == "" else label
        rows.append(record)
    return rows


def _safe_json(obj) -> str:
    """json.dumps with `</` escaped, so speech text cannot prematurely close
    the surrounding <script> tag when embedded into the HTML template."""
    return json.dumps(obj, ensure_ascii=False).replace("</", "<\\/")


def _html(rows: list[dict]) -> str:
    return (
        TEMPLATE.replace("__DATA__", _safe_json(rows))
        .replace("__COLUMNS__", _safe_json([*CONTEXT_COLUMNS, LABEL_COLUMN]))
        .replace("__LABELS__", _safe_json(VALID_LABELS))
        .replace("__LABEL_DEFS__", _safe_json(LABEL_DEFINITIONS))
        .replace("__RULES__", _safe_json(DECISION_RULES))
        .replace("__PM_COLORS__", _safe_json(PM_COLORS))
        .replace("__DEFAULT_PM_COLOR__", DEFAULT_PM_COLOR)
        .replace("__TOTAL__", str(len(rows)))
    )


def main() -> None:
    rows = _load_rows()
    n_done = sum(1 for r in rows if r[LABEL_COLUMN] is not None)
    print(f"Loaded {len(rows)} contributions ({n_done} already annotated in the CSV)")

    output_path = PROCESSED_DIR / OUTPUT_FILENAME
    output_path.write_text(_html(rows), encoding="utf-8")
    print(f"Wrote {output_path}")
    print(f"Open it with:  open {output_path}")


TEMPLATE = r"""<!doctype html>
<html lang="fr">
<head>
<meta charset="utf-8" />
<title>Annotation - sentiment PM</title>
<style>
:root {
  --bg: #f4f5f7; --surface: #ffffff; --surface-2: #eceef2; --ink: #16181d;
  --muted: #5c6270; --line: #dadde3; --accent: #2c6e8e; --accent-bg: #e3eef2;
  --pos: #2f9e6e; --pos-bg: #e4f5ee; --neg: #c9432f; --neg-bg: #fbe9e6;
  --neu: #8a8f99; --neu-bg: #eceef2;
  --mono: ui-monospace, "SF Mono", Menlo, Consolas, monospace;
  --sans: -apple-system, "Segoe UI", Roboto, Helvetica, Arial, sans-serif;
}
@media (prefers-color-scheme: dark) {
  :root {
    --bg: #14161a; --surface: #1b1e24; --surface-2: #21252c; --ink: #e9ecf1;
    --muted: #949cab; --line: #2c313a; --accent: #5fb2d6; --accent-bg: #1b3038;
    --pos: #4fc191; --pos-bg: #163229; --neg: #ef7862; --neg-bg: #3a1f1a;
    --neu: #949cab; --neu-bg: #21252c;
  }
}
* { box-sizing: border-box; }
body {
  margin: 0; font-family: var(--sans); background: var(--bg); color: var(--ink);
  height: 100vh; display: flex; flex-direction: column;
}
header {
  display: flex; align-items: center; gap: 1rem; padding: 0.7rem 1.1rem;
  background: var(--surface); border-bottom: 1px solid var(--line); flex: none;
}
header h1 { font-size: 1rem; font-weight: 700; margin: 0; }
header .spacer { flex: 1; }
#progress { font-family: var(--mono); font-size: 0.85rem; color: var(--muted); }
#progress b { color: var(--ink); }
button {
  font: inherit; border: 1px solid var(--line); background: var(--surface-2);
  color: var(--ink); border-radius: 7px; padding: 0.45rem 0.8rem; cursor: pointer;
}
button:hover { border-color: var(--accent); }
button.primary { background: var(--accent); color: white; border-color: var(--accent); }
main { flex: 1; display: flex; min-height: 0; }

#sidebar {
  width: 340px; flex: none; border-right: 1px solid var(--line); background: var(--surface);
  display: flex; flex-direction: column;
}
#filters { padding: 0.7rem; border-bottom: 1px solid var(--line); display: flex; flex-direction: column; gap: 0.5rem; }
#filters-row { display: flex; gap: 0.5rem; }
#filters select, #filters input {
  font: inherit; padding: 0.35rem 0.5rem; border: 1px solid var(--line); border-radius: 6px;
  background: var(--surface); color: var(--ink); width: 100%;
}
#filters-row select { flex: 1; }
#list { flex: 1; overflow-y: auto; }
.item {
  padding: 0.55rem 0.8rem; border-bottom: 1px solid var(--line); cursor: pointer; font-size: 0.82rem;
}
.item:hover { background: var(--surface-2); }
.item.active { background: var(--accent-bg); border-left: 3px solid var(--accent); }
.item .row1 { display: flex; justify-content: space-between; font-family: var(--mono); color: var(--muted); font-size: 0.72rem; }
.item .row1 .who { display: flex; align-items: center; gap: 0.35rem; }
.item .title { margin-top: 0.15rem; color: var(--ink); overflow: hidden; text-overflow: ellipsis; white-space: nowrap; }
.item .mark { font-weight: 700; }
.item .mark.positive { color: var(--pos); }
.item .mark.negative { color: var(--neg); }
.item .mark.neutral { color: var(--neu); }

.pm-dot {
  display: inline-block; width: 0.6rem; height: 0.6rem; border-radius: 50%;
  flex: none; border: 1px solid rgba(0,0,0,0.15);
}
#reset-filters-btn { width: 100%; }

#detail { flex: 1; overflow-y: auto; padding: 1.3rem 1.6rem 3rem; }
#meta { display: flex; flex-wrap: wrap; gap: 0.4rem 0.8rem; margin-bottom: 1rem; font-size: 0.82rem; color: var(--muted); }
#meta span b { color: var(--ink); font-weight: 600; }
#debate-title { font-size: 1.05rem; font-weight: 700; margin: 0 0 0.6rem; text-wrap: balance; }
#text {
  background: var(--surface); border: 1px solid var(--line); border-radius: 10px;
  padding: 1rem 1.2rem; font-size: 0.95rem; line-height: 1.6; white-space: pre-wrap;
  margin-bottom: 1.3rem; max-height: 45vh; overflow-y: auto;
}
.panel { background: var(--surface); border: 1px solid var(--line); border-radius: 10px; padding: 1rem 1.2rem; margin-bottom: 1rem; }
.panel h2 { font-size: 0.85rem; text-transform: uppercase; letter-spacing: 0.04em; color: var(--muted); margin: 0 0 0.7rem; }

.label-row { display: flex; gap: 0.6rem; }
.label-row button { flex: 1; padding: 0.8rem 0.6rem; font-weight: 600; text-align: left; }
.label-row button .kbd { float: right; font-family: var(--mono); font-weight: 400; opacity: 0.7; }
.label-row button .def { display: block; font-weight: 400; font-size: 0.78rem; color: var(--muted); margin-top: 0.2rem; }
.label-row button.positive.selected { background: var(--pos-bg); border-color: var(--pos); color: var(--pos); }
.label-row button.neutral.selected { background: var(--neu-bg); border-color: var(--neu); color: var(--ink); }
.label-row button.negative.selected { background: var(--neg-bg); border-color: var(--neg); color: var(--neg); }

#rules { font-size: 0.82rem; color: var(--muted); }
#rules li { margin-bottom: 0.35rem; }

#progress-bar-track {
  width: 140px; height: 0.5rem; border-radius: 999px; background: var(--surface-2);
  overflow: hidden; flex: none;
}
#progress-bar-fill {
  height: 100%; background: var(--pos); border-radius: 999px;
  transition: width 0.2s ease;
}
#filter-count { font-size: 0.78rem; color: var(--muted); padding: 0 0.2rem; }

#nav { display: flex; gap: 0.6rem; margin-top: 0.3rem; }
#nav button { flex: 1; }
#kbd-hint { font-size: 0.74rem; color: var(--muted); margin-top: 0.6rem; text-align: center; }
#empty { color: var(--muted); padding: 2rem; text-align: center; }
</style>
</head>
<body>

<header>
  <h1>Annotation - sentiment PM</h1>
  <div id="progress-bar-track"><div id="progress-bar-fill" style="width:0%"></div></div>
  <div id="progress"><b id="progress-n">0</b> / __TOTAL__ annotés</div>
  <div class="spacer"></div>
  <button id="reset-btn">Réinitialiser</button>
  <label class="button" style="display:inline-block;">
    <input type="file" id="import-input" accept=".csv" style="display:none;" />
    <button id="import-btn" type="button">Importer un CSV</button>
  </label>
  <button id="export-btn" class="primary">Exporter le CSV</button>
  <button id="export-json-btn">Exporter le JSON</button>
</header>

<main>
  <div id="sidebar">
    <div id="filters">
      <div id="filters-row">
        <select id="filter-pm"></select>
        <select id="filter-pmqs">
          <option value="">Tous les débats</option>
          <option value="yes">PMQs uniquement</option>
          <option value="no">Hors PMQs</option>
        </select>
      </div>
      <select id="filter-status">
        <option value="">Tous les statuts</option>
        <option value="done">Déjà annotés</option>
        <option value="todo">Non annotés</option>
      </select>
      <input type="text" id="filter-search" placeholder="Recherche (débat, texte)" />
      <button id="reset-filters-btn" type="button">Réinitialiser les filtres</button>
      <div id="filter-count"></div>
    </div>
    <div id="list"></div>
  </div>

  <div id="detail"></div>
</main>

<script>
const DATA = __DATA__;
const LABELS = __LABELS__;
const LABEL_DEFS = __LABEL_DEFS__;
const RULES = __RULES__;
const PM_COLORS = __PM_COLORS__;
const DEFAULT_PM_COLOR = "__DEFAULT_PM_COLOR__";
const STORAGE_KEY = "sentimentAnnotations_v1";
const LABEL_KEYS = { "1": "positive", "2": "neutral", "3": "negative" };

function pmColor(pm) {
  return PM_COLORS[pm] || DEFAULT_PM_COLOR;
}

function pmDot(pm) {
  return `<span class="pm-dot" style="background:${pmColor(pm)}" title="${escapeHtml(pm)}"></span>`;
}

function loadState() {
  let stored = {};
  try { stored = JSON.parse(localStorage.getItem(STORAGE_KEY) || "{}"); } catch (e) {}
  const state = {};
  for (const row of DATA) {
    const fromStorage = stored[row.contribution_ext_id];
    state[row.contribution_ext_id] = fromStorage || { label: row.sentiment_label || null };
  }
  return state;
}

function saveState() {
  localStorage.setItem(STORAGE_KEY, JSON.stringify(annotations));
}

let annotations = loadState();
let currentId = DATA[0].contribution_ext_id;
let filtered = DATA.slice();

function isDone(id) {
  const a = annotations[id];
  return !!(a && a.label);
}

function pmOptions() {
  const sel = document.getElementById("filter-pm");
  const pms = [...new Set(DATA.map(r => r.pm_name))];
  sel.innerHTML = '<option value="">Tous les PM</option>' +
    pms.map(p => `<option value="${p}">${p}</option>`).join("");
}

function applyFilters() {
  const pm = document.getElementById("filter-pm").value;
  const pmqs = document.getElementById("filter-pmqs").value;
  const status = document.getElementById("filter-status").value;
  const search = document.getElementById("filter-search").value.toLowerCase();

  filtered = DATA.filter(r => {
    if (pm && r.pm_name !== pm) return false;
    if (pmqs === "yes" && !r.is_pmqs) return false;
    if (pmqs === "no" && r.is_pmqs) return false;
    if (status === "done" && !isDone(r.contribution_ext_id)) return false;
    if (status === "todo" && isDone(r.contribution_ext_id)) return false;
    if (search) {
      const haystack = (r.debate_section + " " + r.contribution_text).toLowerCase();
      if (!haystack.includes(search)) return false;
    }
    return true;
  });
  renderList();
}

function resetFilters() {
  document.getElementById("filter-pm").value = "";
  document.getElementById("filter-pmqs").value = "";
  document.getElementById("filter-status").value = "";
  document.getElementById("filter-search").value = "";
  applyFilters();
}

function renderList() {
  const countEl = document.getElementById("filter-count");
  const n = filtered.length;
  countEl.textContent = n === DATA.length ? `${n} contributions` : `${n} contributions sur ${DATA.length}`;

  const el = document.getElementById("list");
  if (!filtered.length) {
    el.innerHTML = '<div id="empty">Aucune contribution ne correspond aux filtres.</div>';
    return;
  }
  el.innerHTML = filtered.map(r => {
    const a = annotations[r.contribution_ext_id];
    const mark = a && a.label ? `<span class="mark ${a.label}">&#9679;</span>` : "";
    const active = r.contribution_ext_id === currentId ? "active" : "";
    return `<div class="item ${active}" data-id="${r.contribution_ext_id}">
      <div class="row1"><span class="who">${pmDot(r.pm_name)}${r.sitting_date} · ${escapeHtml(r.pm_name)}</span><span>${mark}</span></div>
      <div class="title">${escapeHtml(r.debate_section)}</div>
    </div>`;
  }).join("");
  [...el.querySelectorAll(".item")].forEach(node => {
    node.addEventListener("click", () => selectItem(node.dataset.id));
  });
}

function escapeHtml(s) {
  return (s || "").replace(/[&<>"']/g, c => ({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]));
}

function selectItem(id) {
  currentId = id;
  renderList();
  renderDetail();
}

function renderDetail() {
  const row = DATA.find(r => r.contribution_ext_id === currentId);
  const a = annotations[currentId] || {};

  const labelButtons = LABELS.map((label, i) => {
    const [title, examples] = LABEL_DEFS[label];
    const selected = a.label === label ? "selected" : "";
    const kbd = i + 1;
    return `<button class="${label} ${selected}" data-label="${label}">
      ${label === "positive" ? "Positif" : label === "neutral" ? "Neutre" : "Négatif"}
      <span class="kbd">${kbd}</span>
      <span class="def">${title}</span>
    </button>`;
  }).join("");

  document.getElementById("detail").innerHTML = `
    <div id="meta">
      <span><b>${row.sitting_date}</b></span>
      <span>${pmDot(row.pm_name)} ${escapeHtml(row.pm_name)}</span>
      <span>${row.is_pmqs ? "PMQs" : "Autre débat"}</span>
    </div>
    <h2 id="debate-title">${escapeHtml(row.debate_section)}</h2>
    <div id="text">${escapeHtml(row.contribution_text)}</div>

    <div class="panel">
      <h2>Sentiment - quel est le ton dominant de cette contribution ?</h2>
      <div class="label-row">${labelButtons}</div>
    </div>

    <div class="panel">
      <h2>Règles de décision</h2>
      <ul id="rules">${RULES.map(r => `<li>${r}</li>`).join("")}</ul>
    </div>

    <div id="nav">
      <button id="prev-btn">&larr; Précédent</button>
      <button id="next-btn">Suivant &rarr;</button>
    </div>
    <div id="kbd-hint">&larr;/&rarr; ou J/K pour naviguer · 1 Positif · 2 Neutre · 3 Négatif</div>
  `;

  [...document.querySelectorAll(".label-row button")].forEach(btn => {
    btn.addEventListener("click", () => setLabel(btn.dataset.label));
  });
  document.getElementById("prev-btn").addEventListener("click", () => step(-1));
  document.getElementById("next-btn").addEventListener("click", () => step(1));

  updateProgress();
}

function setLabel(label) {
  annotations[currentId] = { label };
  saveState();
  renderList();
  renderDetail();
}

function step(delta) {
  const idx = filtered.findIndex(r => r.contribution_ext_id === currentId);
  const next = filtered[idx + delta];
  if (next) selectItem(next.contribution_ext_id);
}

function updateProgress() {
  const done = DATA.filter(r => isDone(r.contribution_ext_id)).length;
  document.getElementById("progress-n").textContent = done;
  const pct = DATA.length ? Math.round((100 * done) / DATA.length) : 0;
  document.getElementById("progress-bar-fill").style.width = `${pct}%`;
}

document.addEventListener("keydown", e => {
  if (e.target.tagName === "INPUT" || e.target.tagName === "SELECT") return;
  if (e.key === "ArrowRight" || e.key.toLowerCase() === "j") step(1);
  else if (e.key === "ArrowLeft" || e.key.toLowerCase() === "k") step(-1);
  else if (LABEL_KEYS[e.key]) setLabel(LABEL_KEYS[e.key]);
});

document.getElementById("filter-pm").addEventListener("change", applyFilters);
document.getElementById("filter-pmqs").addEventListener("change", applyFilters);
document.getElementById("filter-status").addEventListener("change", applyFilters);
document.getElementById("filter-search").addEventListener("input", applyFilters);
document.getElementById("reset-filters-btn").addEventListener("click", resetFilters);

document.getElementById("reset-btn").addEventListener("click", () => {
  if (confirm("Effacer toutes les annotations de ce navigateur ? Cette action est irréversible.")) {
    localStorage.removeItem(STORAGE_KEY);
    annotations = loadState();
    renderList();
    renderDetail();
  }
});

function csvField(value) {
  const s = value === null || value === undefined ? "" : String(value);
  if (/[",\n]/.test(s)) return '"' + s.replace(/"/g, '""') + '"';
  return s;
}

function downloadBlob(content, mimeType, filename) {
  const blob = new Blob([content], { type: mimeType });
  const url = URL.createObjectURL(blob);
  const a = document.createElement("a");
  a.href = url;
  a.download = filename;
  a.click();
  URL.revokeObjectURL(url);
}

function buildExportRecords() {
  return DATA.map(row => {
    const a = annotations[row.contribution_ext_id] || {};
    return { ...row, sentiment_label: a.label || "" };
  });
}

document.getElementById("export-btn").addEventListener("click", () => {
  const columns = __COLUMNS__;
  const lines = [columns.join(",")];
  for (const record of buildExportRecords()) {
    lines.push(columns.map(c => csvField(record[c])).join(","));
  }
  downloadBlob(lines.join("\n"), "text/csv;charset=utf-8", "sentiment_annotation_sample.csv");
});

document.getElementById("export-json-btn").addEventListener("click", () => {
  const json = JSON.stringify(buildExportRecords(), null, 2);
  downloadBlob(json, "application/json;charset=utf-8", "sentiment_annotation_sample.json");
});

function parseCsv(text) {
  const rows = [];
  let row = [], field = "", inQuotes = false;
  for (let i = 0; i < text.length; i++) {
    const c = text[i];
    if (inQuotes) {
      if (c === '"' && text[i + 1] === '"') { field += '"'; i++; }
      else if (c === '"') { inQuotes = false; }
      else { field += c; }
    } else {
      if (c === '"') inQuotes = true;
      else if (c === ",") { row.push(field); field = ""; }
      else if (c === "\n") { row.push(field); rows.push(row); row = []; field = ""; }
      else if (c === "\r") { /* skip */ }
      else field += c;
    }
  }
  if (field.length || row.length) { row.push(field); rows.push(row); }
  const header = rows.shift();
  return rows.filter(r => r.length === header.length).map(r =>
    Object.fromEntries(header.map((h, i) => [h, r[i]]))
  );
}

document.getElementById("import-btn").addEventListener("click", () => {
  document.getElementById("import-input").click();
});
document.getElementById("import-input").addEventListener("change", e => {
  const file = e.target.files[0];
  if (!file) return;
  file.text().then(text => {
    const records = parseCsv(text);
    let n = 0;
    for (const rec of records) {
      if (!annotations[rec.contribution_ext_id]) continue;
      if (!LABELS.includes(rec.sentiment_label)) continue;
      annotations[rec.contribution_ext_id] = { label: rec.sentiment_label };
      n++;
    }
    saveState();
    renderList();
    renderDetail();
    alert(`${n} annotations importées.`);
  });
});

pmOptions();
applyFilters();
selectItem(currentId);
</script>
</body>
</html>
"""


if __name__ == "__main__":
    main()
